const products = [
  {
    id: 1,
    catagories: "Drill Machine",
    name: "Granting",
    img: "https://i.ibb.co/Pr73mgS/products1.webp",
    img2: "https://i.ibb.co/rmrz3XV/products2.webp",
    img3: "https://i.ibb.co/LYW0BdW/products3.webp",
    img3: "https://i.ibb.co/KDB4CLN/products4.webp",
    price: 32,
    latestPrice: 30,
    rating: 4,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },

  {
    id: 2,
    catagories: "Drill Machine",
    name: "Hand Grill",
    img: "https://i.ibb.co/rmrz3XV/products2.webp",
    img2: "https://i.ibb.co/Pr73mgS/products1.webp",
    img3: "https://i.ibb.co/LYW0BdW/products3.webp",
    img4: "https://i.ibb.co/KDB4CLN/products4.webp",
    price: 25,
    latestPrice: 28,
    rating: 4,
    reviewer: 5,
    stock: 120,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },

  {
    id: 2,
    catagories: "Drill Machine",
    name: "Granting",
    img: "https://i.ibb.co/LYW0BdW/products3.webp",
    img2: "https://i.ibb.co/Pr73mgS/products1.webp",
    img3: "https://i.ibb.co/rmrz3XV/products2.webp",
    img4: "https://i.ibb.co/KDB4CLN/products4.webp",
    price: 32,
    latestPrice: 30,
    rating: 4,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },

  {
    id: 3,
    catagories: "Drill Machine",
    name: "Baby  Drill",
    img: "https://i.ibb.co/KDB4CLN/products4.webp",
    img2: "https://i.ibb.co/Pr73mgS/products1.webp",
    img3: "https://i.ibb.co/rmrz3XV/products2.webp",
    img4: "https://i.ibb.co/LYW0BdW/products3.webp",
    price: 18,
    latestPrice: 15,
    rating: 5,
    reviewer: 8,
    stock: 180,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },

  {
    id: 4,
    catagories: "Power Saw",
    name: "Big Drill",
    img: "https://i.ibb.co/KDB4CLN/products4.webp",
    img2: "https://i.ibb.co/Pr73mgS/products1.webp",
    img3: "https://i.ibb.co/rmrz3XV/products2.webp",
    img4: "https://i.ibb.co/LYW0BdW/products3.webp",
    price: 32,
    latestPrice: 30,
    rating: 4,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },

  {
    id: 5,
    catagories: "Power Saw",
    name: "Dill Machine",
    img: "https://i.ibb.co/KDB4CLN/products4.webp",
    img2: "https://i.ibb.co/Pr73mgS/products1.webp",
    img3: "https://i.ibb.co/rmrz3XV/products2.webp",
    img4: "https://i.ibb.co/LYW0BdW/products3.webp",
    price: 67,
    latestPrice: 65,
    rating: 3,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },

  {
    id: 6,
    catagories: "Power Saw",
    name: "Big Drill",
    img: "https://i.ibb.co/Pr73mgS/products1.webp",
    img2: "https://i.ibb.co/KDB4CLN/products4.webp",
    img3: "https://i.ibb.co/rmrz3XV/products2.webp",
    img4: "https://i.ibb.co/LYW0BdW/products3.webp",
    price: 44,
    latestPrice: 40,
    rating: 4,
    reviewer: 9,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },

  {
    id: 7,
    catagories: "Power Saw",
    name: "Hand Granting",
    img: "https://i.ibb.co/rmrz3XV/products2.webp",
    img2: "https://i.ibb.co/KDB4CLN/products4.webp",
    img3: "https://i.ibb.co/Pr73mgS/products1.webp",
    img4: "https://i.ibb.co/LYW0BdW/products3.webp",
    price: 63,
    latestPrice: 60,
    rating: 4,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },

  {
    id: 8,
    catagories: "Power Saw",
    name: "Cutting Big",
    img: "https://i.ibb.co/LYW0BdW/products3.webp",
    img2: "https://i.ibb.co/rmrz3XV/products2.webp",
    img3: "https://i.ibb.co/KDB4CLN/products4.webp",
    img4: "https://i.ibb.co/Pr73mgS/products1.webp",
    price: 32,
    latestPrice: 30,
    rating: 4,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },

  {
    id: 9,
    catagories: "Hardware",
    name: "Hammer Drill Big",
    img: "https://i.ibb.co/LYW0BdW/products3.webp",
    img2: "https://i.ibb.co/rmrz3XV/products2.webp",
    img3: "https://i.ibb.co/KDB4CLN/products4.webp",
    img4: "https://i.ibb.co/Pr73mgS/products1.webp",
    price: 32,
    latestPrice: 30,
    rating: 4,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },
  {
    id: 10,
    catagories: "Hardware",
    name: "Cutting Big",
    img: "https://i.ibb.co/rmrz3XV/products2.webp",
    img2: "https://i.ibb.co/LYW0BdW/products3.webp",
    img3: "https://i.ibb.co/KDB4CLN/products4.webp",
    img4: "https://i.ibb.co/Pr73mgS/products1.webp",
    price: 32,
    latestPrice: 30,
    rating: 4,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },
  {
    id: 11,
    catagories: "Hardware",
    name: "Baby Hammer",
    img: "https://i.ibb.co/KDB4CLN/products4.webp",
    img2: "https://i.ibb.co/LYW0BdW/products3.webp",
    img3: "https://i.ibb.co/rmrz3XV/products2.webp",
    img4: "https://i.ibb.co/Pr73mgS/products1.webp",
    price: 62,
    latestPrice: 59,
    rating: 4,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },
  {
    id: 12,
    catagories: "Hardware",
    name: "Hand Drill",
    img: "https://i.ibb.co/Pr73mgS/products1.webp",
    img2: "https://i.ibb.co/LYW0BdW/products3.webp",
    img3: "https://i.ibb.co/rmrz3XV/products2.webp",
    img4: "https://i.ibb.co/KDB4CLN/products4.webp",
    price: 44,
    latestPrice: 42,
    rating: 4,
    reviewer: 2,
    stock: 150,
    minOrder: 10,
    description:
      "Everything you need for a trip to the gym will fit inside this surprisingly spacious Products Name Here. Stock it with a water bottle, change of clothes, pair of shoes, and even a few beauty products. Fits inside a locker and zips shut for security.",
    SpecialFeature: [
      "Slip pocket on front.",
      "Contrast piping",
      "Durable nylon construction.",
      "Contrast piping",
    ],
  },
];
